PRIORITY_INCREMENT = 100000
return {
	PRIORITY_BACKGROUND: 1 * PRIORITY_INCREMENT
	PRIORITY_OBJECT: 2 * PRIORITY_INCREMENT
	PRIORITY_FOREGROUND: 3 * PRIORITY_INCREMENT
	PRIORITY_INTERFACE: 4 * PRIORITY_INCREMENT

	LEFT_TOP: {0,0}
	CENTER_TOP: {0.5,0}
	RIGHT_TOP: {1.0,0}

	LEFT_CENTER: {0,0.5}
	CENTER: {0.5,0.5}
	RIGHT_CENTER: {1.0,0.5}

	LEFT_BOTTOM: {0,1.0}
	CENTER_BOTTOM: {0.5,1.0}
	RIGHT_BOTTOM: {1.0,1.0}
}